
USE HoangTien2k3
GO


-- Gộp thông tin 2 bảng GIAOVIEN và GV_DT để lấy ra thông tin của MAGV, HOTEN, DIENTHOAI
SELECT GIAOVIEN.MAGV, GIAOVIEN.HOTEN, GV_DT.DIENTHOAI
FROM GIAOVIEN
LEFT JOIN GV_DT
ON GIAOVIEN.MAGV = GV_DT.MAGV

